# -*- coding: utf-8 -*-
"""M6L3_Algilama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8CNodrqd9O7ONYC4dhbrLkDUAEZEn2y
"""

!pip install ImageAI

!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/3.0.0-pretrained/yolov3.pt

from imageai.Detection import ObjectDetection

detector = ObjectDetection()
model_path = "yolov3.pt"
detector.setModelTypeAsYOLOv3()
detector.setModelPath(model_path)
detector.loadModel()

"""Modelin tanıyabileceği şeyler"""

detector.CustomObjects()

detections = detector.detectObjectsFromImage(
    input_image="yol.jpg",
    output_image_path="output_image.jpg",
    minimum_percentage_probability=40)

detections

def detectOnRoad(image):
  detector = ObjectDetection()
  model_path = "yolov3.pt"
  detector.setModelTypeAsYOLOv3()
  detector.setModelPath(model_path)
  detector.loadModel()

  detections = detector.detectObjectsFromImage(
    input_image= image,
    output_image_path="output_image.jpg",
    minimum_percentage_probability=40)
  return detections

def analyze_objects(detections):
    road_users = []
    valid_names = {"car", "bus", "train", "truck", "person", "bicycle"}

    current_id = 0
    prev_name = None  # Bir önceki nesnenin adını tutmak için

    for item in detections:
        name = item.get("name")

        # Sadece listedeki geçerli nesne tiplerini işleme alıyoruz
        if name in valid_names:
            if prev_name is not None and name != prev_name:
                # İsim öncekinden farklıysa id'yi sıfırla
                current_id = 0

            # Formatı listeye ekle (Örn: "0) car")
            road_users.append(f"{current_id}) {name}")

            # Bir sonraki eleman için hazırlık yap
            current_id += 1
            prev_name = name

    return road_users

analyze_objects(detections)

def road_rules():
  print("SafetyAI size iyi yolculuklar diler.")
  print("Emniyet kemerlerinizi bağlayınız.")
  print("Hız Sınırlarına dikkat ediniz.")
  print("Yaya geçitlerinde yayalara yol veriniz.")
  print("Kırmızı Işıklarda durduğunuz gibi sarıda da durunuz.")
  print("Tespit edilenler: ")

road_rules()
print(analyze_objects(detectOnRoad("yol.jpg")))